### ISSUE TITLE
時間と温度表示の部分をコンポーネント化

### ISSUE THREAD

**Issue by jumang4423** [Andyyyy64/Berlinweatherapp#2]
# DUE: 6/4
- [該当箇所](https://github.com/Andyyyy64/Berlinweatherapp/blob/fab1790f74c9684cf82b83eb5925037c6e9d6943/weatherapp/src/App.vue#L53)

- 該当箇所をコンポーネント化する
- propsを通じて{temp: number, time: string}を通す

**Comment by jumang4423** [comment]
こんな感じかな？(Vueしらん)

<img width="556" alt="Screen Shot 2022-06-01 at 21 47 40" src="https://user-images.githubusercontent.com/63630786/171407930-b5b2da94-9b9a-4e00-9ffb-70eee1c81c58.png">

![FUBWKfqXEAUhoy6](https://user-images.githubusercontent.com/63630786/171407990-439da9a5-5da6-4b47-ba29-3030242f47b0.jpeg)

**Comment by Andyyyy64** [comment]
done!
